// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230160228_AddIsTopListAndNormalizedNameAndMergeCompetences")]
    partial class AddIsTopListAndNormalizedNameAndMergeCompetences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApp.Domain.Entities.ApplicationUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ApplicationUserProfiles");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsTopList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComputedColumnSql("UPPER(LTRIM(RTRIM([Name])))", true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Kompetenskatalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programmeringsspråk",
                            IsTopList = true,
                            Name = "C#",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            IsTopList = true,
                            Name = ".NET",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            IsTopList = true,
                            Name = "ASP.NET Core",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            IsTopList = true,
                            Name = "MVC",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Backend",
                            IsTopList = true,
                            Name = "EF Core",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Category = "Backend",
                            IsTopList = true,
                            Name = "LINQ",
                            NormalizedName = "",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Category = "Programmeringsspråk",
                            IsTopList = true,
                            Name = "SQL",
                            NormalizedName = "",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 8,
                            Category = "DevOps & Drift",
                            IsTopList = true,
                            Name = "Git",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = "DevOps & Drift",
                            IsTopList = true,
                            Name = "Docker",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            Category = "DevOps & Drift",
                            IsTopList = true,
                            Name = "Azure",
                            NormalizedName = "",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 11,
                            Category = "DevOps & Drift",
                            IsTopList = true,
                            Name = "Linux",
                            NormalizedName = "",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 12,
                            Category = "Backend",
                            IsTopList = true,
                            Name = "REST API",
                            NormalizedName = "",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 14,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "Java",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "Python",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 16,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "JavaScript",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 17,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "TypeScript",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 19,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "HTML",
                            NormalizedName = "",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 20,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "CSS",
                            NormalizedName = "",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 21,
                            Category = "Programmeringsspråk",
                            IsTopList = false,
                            Name = "Bash",
                            NormalizedName = "",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 25,
                            Category = "Backend",
                            IsTopList = false,
                            Name = "Web API",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 28,
                            Category = "Backend",
                            IsTopList = false,
                            Name = "SignalR",
                            NormalizedName = "",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 29,
                            Category = "Frontend",
                            IsTopList = false,
                            Name = "React",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 30,
                            Category = "Frontend",
                            IsTopList = false,
                            Name = "Vue",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 31,
                            Category = "Frontend",
                            IsTopList = false,
                            Name = "Angular",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 32,
                            Category = "Frontend",
                            IsTopList = false,
                            Name = "Vite",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 33,
                            Category = "Frontend",
                            IsTopList = false,
                            Name = "Tailwind",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 34,
                            Category = "Frontend",
                            IsTopList = false,
                            Name = "Bootstrap",
                            NormalizedName = "",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 35,
                            Category = "Databaser",
                            IsTopList = false,
                            Name = "SQL Server",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 36,
                            Category = "Databaser",
                            IsTopList = false,
                            Name = "PostgreSQL",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 37,
                            Category = "Databaser",
                            IsTopList = false,
                            Name = "MySQL",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 38,
                            Category = "Databaser",
                            IsTopList = false,
                            Name = "SQLite",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 39,
                            Category = "Databaser",
                            IsTopList = false,
                            Name = "MongoDB",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 40,
                            Category = "Databaser",
                            IsTopList = false,
                            Name = "Redis",
                            NormalizedName = "",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 42,
                            Category = "DevOps & Drift",
                            IsTopList = false,
                            Name = "GitHub",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 43,
                            Category = "DevOps & Drift",
                            IsTopList = false,
                            Name = "CI/CD",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 45,
                            Category = "DevOps & Drift",
                            IsTopList = false,
                            Name = "Kubernetes",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 47,
                            Category = "DevOps & Drift",
                            IsTopList = false,
                            Name = "Nginx",
                            NormalizedName = "",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 49,
                            Category = "DevOps & Drift",
                            IsTopList = false,
                            Name = "AWS",
                            NormalizedName = "",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 50,
                            Category = "Test & Kvalitet",
                            IsTopList = false,
                            Name = "xUnit",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 51,
                            Category = "Test & Kvalitet",
                            IsTopList = false,
                            Name = "NUnit",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 52,
                            Category = "Test & Kvalitet",
                            IsTopList = false,
                            Name = "Integration Tests",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 53,
                            Category = "Test & Kvalitet",
                            IsTopList = false,
                            Name = "Unit Tests",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 54,
                            Category = "Test & Kvalitet",
                            IsTopList = false,
                            Name = "Logging",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 55,
                            Category = "Test & Kvalitet",
                            IsTopList = false,
                            Name = "Serilog",
                            NormalizedName = "",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 56,
                            Category = "Säkerhet",
                            IsTopList = false,
                            Name = "OWASP",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 57,
                            Category = "Säkerhet",
                            IsTopList = false,
                            Name = "HTTPS/TLS",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 58,
                            Category = "Säkerhet",
                            IsTopList = false,
                            Name = "JWT",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 59,
                            Category = "Säkerhet",
                            IsTopList = false,
                            Name = "OAuth2",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 60,
                            Category = "Arkitektur & Metoder",
                            IsTopList = false,
                            Name = "Clean Architecture",
                            NormalizedName = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 61,
                            Category = "Arkitektur & Metoder",
                            IsTopList = false,
                            Name = "SOLID",
                            NormalizedName = "",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 62,
                            Category = "Arkitektur & Metoder",
                            IsTopList = false,
                            Name = "DDD",
                            NormalizedName = "",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 63,
                            Category = "Arkitektur & Metoder",
                            IsTopList = false,
                            Name = "Agile",
                            NormalizedName = "",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 64,
                            Category = "Arkitektur & Metoder",
                            IsTopList = false,
                            Name = "Scrum",
                            NormalizedName = "",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 65,
                            Category = "Arkitektur & Metoder",
                            IsTopList = false,
                            Name = "TDD",
                            NormalizedName = "",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.DirectMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SentUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SentUtc");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SortOrder");

                    b.ToTable("Utbildningar");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avsandare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Skickad")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meddelanden");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Headline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedProjectsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("IsPublic");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Profiler");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.ProfileVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("VisitedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VisitorIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("VisitedUtc");

                    b.ToTable("ProfilBesok");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("ProjectImagePath");

                    b.Property<string>("KortBeskrivning")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("TechStackKeysCsv")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("Projekt");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.ProjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ConnectedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjektAnvandare");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kompetenser");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.UserCompetence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CompetenceId")
                        .IsUnique();

                    b.ToTable("AnvandarKompetenser");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReadUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("SentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("RecipientUserId", "IsRead", "SentUtc");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Years")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SortOrder");

                    b.ToTable("Erfarenheter");
                });

            modelBuilder.Entity("WebApp.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstNameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasCompletedAccountProfile")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCreatedCv")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfilePrivate")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastNameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumberDisplay")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApp.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApp.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApp.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Domain.Entities.ApplicationUserProfile", b =>
                {
                    b.HasOne("WebApp.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Education", b =>
                {
                    b.HasOne("WebApp.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("WebApp.Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
